import data
import time

def bok():
    print()
    print("Hotel Booking")
    print()
    print("Hotel Details:")
    print("Write The Name Of Hotel")
    ht = input("Enter Hotel Name Here: ")
    print()
    print("Want To Book Hotel Room For How Many Days?")
    dy = int(input("Enter Number Of Days Here: "))
    print()
    print("Check-in Date (DD/MM/YY)")
    bk1 = input("Enter Date Here: ")
    print()
    print("Check-out Date (DD/MM/YY)")
    bk2 = input("Enter Date Here: ")
    print()
    print("Customer Details:")
    print("Customer Name")
    cn = input("Enter Your Name: ")
    print()
    print("Customer Phone Number")
    cp = int(input("Enter Your Phone Number: "))

    if ht == "flamingo" or ht == "Flamingo":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e1.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*500)
        print("="*20)
        print()
        
    elif ht == "sunset" or ht == "Sunset":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e2.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*450)
        print("="*20)
        print()
        
    elif ht == "seashore" or ht == "Seashore":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e3.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*350)
        print("="*20)
        print()
        
    elif ht == "sunrise" or ht == "Sunrise":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e4.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*320)
        print("="*20)
        print()
        
    elif ht == "mid night" or ht == "Mid night":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e5.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*550)
        print("="*20)
        print()
        
    elif ht == "eight" or ht == "Eight":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e6.info())
        print("Check-in Date: ", bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*510)
        print("="*20)
        print()
        
    elif ht == "olive" or ht == "Olive":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e7.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*290)
        print("="*20)
        print()
        
    elif ht == "nv" or ht == "NV":
        print("="*20)   
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e8.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*480)
        print("="*20)
        print()
        
    elif ht == "indigo" or ht == "Indigo":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e9.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*450)
        print()
        print("="*20)
        
    elif ht == "hotel Blue" or ht == "Hotel Blue" or ht == "Blue" or ht == "blue":
        print("="*20)
        print("Your Bill:")
        print()
        print("Customer Name: ",cn)
        print("Customer Phone Number ",cp)
        print(data.e10.info())
        print("Check-in Date: ",bk1)
        print("Check-out Date: ",bk2)
        print("Total Bill: ",dy*270)
        print()
        print("="*20)
        
    else:
        print("="*20)
        print("No Hotel Available")
        print()

    print("*Note: Extra Fees Would Be Charged If A Costumer Stays In Hotel After Check-out Date.")
    print()
    
    print("1. Confirm Booking?", "\n""2. Cancel")
    py1 = int(input("Enter Your Choice: "))
    print()

    if py1 == 1:
        print("Account Number")
        an = input("Enter Your Account Number Here: ")
        print()
        print("Account Password")
        acpn = input("Enter Your Password Here: ")
        print()
        print("Wait Few Moment")
        time.sleep(2)
        print(".")
        time.sleep(1)
        print(".")
        time.sleep(2)
        print("Ha Ha Ha Ha Ha!")
        print()
        time.sleep(2)
        print("You Got Scammed!")
        print()
        time.sleep(2)
        print("I Did Not Book A Room.")
        print()
        time.sleep(2)
        print("This Money Will Go In My Bank Account.")
        print()
        time.sleep(2)
        print("Do You Think This Is Evil?")
        print()
        time.sleep(2)
        print("Then Hear This...")
        print()
        time.sleep(2)
        print("Yes! I Am Evil!!!!")
        print()
        time.sleep(2)
        print("Ha Ha Ha Ha Ha!")
        print()
        time.sleep(3)
        print("Just Kidding!")
        print()
        time.sleep(2)
        print("Room Has Been Successfuly Booked")
        print()
        time.sleep(2)
        print("Take The Screenshot of The Bill.")
        print()
        time.sleep(2)
        print("Thank You!")

    elif py1 == 2:
        print("Why? Please Book Room For Atleast One Day!")

    else:
        print("Invalid Choice")
        print()
        print(bok())
   

